version: '3.8'

services:
  backend:
    build: 
      context: ../../backend  # 백엔드 디렉토리를 build context로 설정
      dockerfile: ../infrastructure/docker/backend/Dockerfile  # Dockerfile의 상대 경로
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ../../backend:/app  # 소스 코드 마운트
      - /app/node_modules
    networks:
      - app-network

  terminal-service:
    build:
      context: ./terminal
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge